/**/mqtt_client:
  ros__parameters:
    broker:
      host: '6568851381634f73af5c5631e79edcce.s1.eu.hivemq.cloud'
      port: 8883
      user: 'raspi_usv1'
      pass: 'Raspi_usv1'
      tls:
        enabled: true

    bridge:
      ros2mqtt:
        ros_topics:
          - 'core/gps'
          - 'core/heading'
          - 'core/battery0'
          - 'core/temperature'
          - 'core/is_armed'
          - 'core/flight_mode'
          - 'origin_gps'
        core/gps:
          mqtt_topic: 'waraps/unit/surface/real/MiniUSV1/sensor/gps'
        core/heading:
          mqtt_topic: 'waraps/unit/surface/real/MiniUSV1/sensor/heading'
        core/battery0:
          mqtt_topic: 'waraps/unit/surface/real/MiniUSV1/sensor/battery0'
        core/temperature:
          mqtt_topic: 'waraps/unit/surface/real/MiniUSV1/sensor/temperature'
        core/is_armed:
          mqtt_topic: 'waraps/unit/surface/real/MiniUSV1/sensor/is_armed'
        core/flight_mode:
          mqtt_topic: 'waraps/unit/surface/real/MiniUSV1/sensor/flight_mode'
        origin_gps:
          mqtt_topic: 'waraps/unit/surface/real/origin_gps'