/**/rover:
  ros__parameters:
    possible_addresses:
      - 'udpin:172.17.0.1:14550'
      - 'udpin:localhost:14550'
      # - '/dev/serial0'

    subscribers:
      steering: 'control/steering'
      throttle: 'control/throttle'

    publishers:
      gps: 'core/gps'
      heading: 'core/heading'
      imu: 'core/imu'
      battery0: 'core/battery0'
      temperature: 'core/temperature'
      system_state: 'core/is_armed'
      flight_mode: 'core/flight_mode'

    path_pub_rate: 2.0    # Should be between 1.0 to 5.0 Hz